# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examv3', '0002_remove_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('travel_date_from', models.DateField()),
                ('travel_date_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_created', to='examv3.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_joiners',
            field=models.ManyToManyField(related_name='trips_goingto', to='examv3.User'),
        ),
    ]
